
  name: omen_vault_v2
description: A new Flutter project for Omen Vault.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  memguard: ^2.1.4
  local_auth: ^2.1.6
  google_generative_ai: ^0.2.2
  cupertino_icons: ^1.0.2
  purchases_flutter: ^8.0.0
  purchases_ui_flutter: ^8.0.0
  firebase_auth: ^4.16.0
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

